sky:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out_github
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNEtbZx2ZUPnLhravFj
    access-key-secret: D94hAPKuDDJCaBrP30jTG856z8lpkI
    bucket-name: sky-take-out-pzp
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 9

