sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out_github
    username: root
    password: root

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNEtbZx2ZUPnLhravFj
    access-key-secret: D94hAPKuDDJCaBrP30jTG856z8lpkI
    bucket-name: sky-take-out-pzp
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx9155a53b4ed26217
    secret: a27f912cba432fe7941ef654f5deba97
    notify-url: https://6245cef7.rl.cpolar.top/notify/paySucess
    refund-notify-url: https://6245cef7.rl.cpolar.top/notify/refundSucess
